### ISSUE TITLE
HTML&CSS Kata: Custom Radio Buttons

### ISSUE THREAD

**Issue by codingbootcampseu** [BringsCoding/bootcamp-schedule#47]
Create a custom radio buttons [like this](https://coding-katas.netlify.app/custom-radio-buttons/) using CSS only.

![image](https://user-images.githubusercontent.com/16404104/123048429-b06cb400-d3fe-11eb-95c3-2a203fafc7c1.png)

__Requirements__

- Animate the state change from selected to unselected (and vice versa)
- Show the focus state
- Use semantic markup to not break keyboard input

__Hints__

Use `all: unset;` to reset all styles for an input element.

```css
.custom-radio-button { 
  all: unset;
  /* Your checkbox styles */
}
```

A pseudo element (`::before` or `::after`) can be used to display the selected state (which can then be animated).

```css
.custom-radio::before { 
  content: '';
  display: block;
  ...
}
```

Don't forget to include the name attribute to be able so switch between the different options.

```html
<input class="custom-radio" type="radio" value="one" name="test" checked />
<input class="custom-radio" type="radio" value="two" name="test" />
<input class="custom-radio" type="radio" value="three" name="test" />
```
